[package]
name = "peekfbx"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "args"
# path = "src/main.rs"


[dependencies]
crossterm = "0.25"
num = "0.4.1"
rand = "0.8.5"

[lib]
proc-macro = true